version: "3"
services:    
    ffliveparse-app:
        build:
            context: "../"
            dockerfile: "docker/app/Dockerfile"
        ports:
            - "31593:31593/udp"
        env_file:
            - "docker.env"
        restart: always
        volumes:
            - "ffliveparse-data:/app/data/database"
            - "ffliveparse-logging:/app/data/logging"
            - "/mnt/ffliveparse_logs:/app/data/logs"

    ffliveparse-nginx:
        build: "nginx/"
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - "docker.env"
        links:
            - "ffliveparse-app"
        restart: always
        volumes:
            - "/etc/letsencrypt:/etc/letsencrypt"
            - "/var/www/letsencrypt:/var/www/letsencrypt"

volumes:
    "ffliveparse-data": 
        external:
            name: "ffliveparse-data"
    
    "ffliveparse-logging":