version: "3"
services:    
    ffliveparse-app:
        build:
            context: "../"
            dockerfile: "docker/app/Dockerfile"
        ports:
            - "31593:31593/udp"
        env_file:
            - "docker.env"
        links:
            - "ffliveparse-mysql"
        volumes:
            - "ffliveparse-data:/app/data"

    ffliveparse-nginx:
        build: "nginx/"
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - "docker.env"
        links:
            - "ffliveparse-app"
        volumes:
            - "/etc/letsencrypt:/etc/letsencrypt"
            - "/var/www/letsencrypt:/var/www/letsencrypt"

volumes:
    "ffliveparse-data": 
        external:
            name: "ffliveparse-data"